[package]
name = "bench_midpoint"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
num-bigint = "0.4"
rand = "0.8"

[[bench]]
name = "midpoint"
harness = false
